;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mb-cmd-toggle-comment
        mtg-deck-sideboard-toggle
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        shift-number-down
        ))

(setq mc/cmds-to-run-once
      '(
        mb-cmd-control-mode-off
        mb-cmd-control-mode-on
        smart-region
        ))
