;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-quotes
        electric-pair-delete-pair
        indent-for-tab-command
        indent-tools-indent
        markdown-cycle
        markdown-outdent-or-delete
        mb-cmd-toggle-comment
        mtg-deck-sideboard-toggle
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        shift-number-down
        shift-number-up
        string-inflection-underscore
        string-inflection-camelcase
        string-inflection-lower-camelcase
        string-inflection-underscore
        string-inflection-upcase
        string-inflection-kebab-case
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        mb-cmd-control-mode-off
        mb-cmd-control-mode-on
        smart-region
        ))
