;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mwim-beginning-of-code-or-line
	mwim-end-of-code-or-line
	))

(setq mc/cmds-to-run-once
      '(
	my/control-mode-off
	my/control-mode-on
	smart-region
	))
